### ISSUE TITLE
Default window width too small to display all the buttons

### ISSUE THREAD

**Issue by Tuxicoman2** [jsxc/jsxc#1004]
![Capture d’écran de 2021-01-14 00-52-54](https://user-images.githubusercontent.com/45998330/104526559-fed18780-5602-11eb-8ef1-e21dde0ed943.png)

### Expected behavior
When opening a chat chat window, all the buttons should be visible

### Actual behavior
The attachement and encryption button are partially hidden

### Steps to reproduce the behavior
1. Click on contact on the roster to display the chat window.
2.
3.

### Environment
- 4.2.1
- Debian testing
- Firefox 78.6

**Comment by Tuxicoman2** [comment]
[increase_default_width.txt](https://github.com/jsxc/jsxc/files/5811623/increase_default_width.txt)

patch proposal

**Comment by mightymop** [comment]
This should have been fixed by commit: https://github.com/jsxc/jsxc/commit/0fb3cd90f1f7db668ac7b2fef1dd40764eb340d3

**Comment by Tuxicoman2** [comment]
I'm using 2a20ca67e99c0d9fdfe83450381fdfdebf30c58a so seems not :)

Another patch proposal that can replace the previous one if you prefer to keep the small window size.
[message_input_minwidth.txt](https://github.com/jsxc/jsxc/files/5811668/message_input_minwidth.txt)

**Comment by mightymop** [comment]
> 
> 
> I'm using [2a20ca6](https://github.com/jsxc/jsxc/commit/2a20ca67e99c0d9fdfe83450381fdfdebf30c58a) so seems not :)
> 
> Another patch proposal that can replace the previous one if you prefer to keep the small window size.
> [message_input_minwidth.txt](https://github.com/jsxc/jsxc/files/5811668/message_input_minwidth.txt)

Strange... i pulled the master and i dont have this issue anymore right now ... which browser do you use?

**Comment by Tuxicoman2** [comment]
I still have the issue with 4.2.1-git.16874df5 
I use Firefox 78.6ESR on Linux (Debian prefers to use the ESR+latest security patch than the mainstream version)
Chromium layout seems OK (but font is serif which is ugly...)

**Comment by sualko** [comment]
Thanks for reporting this issue and providing proper patches. Generally I don't like to fix stuff I don't understand :smile:. Do you know why FF ESR has this issue?

**Comment by Tuxicoman2** [comment]
I guess, because you never define min-width for the input entry, the browser has to define one.
My 2nd patch just explicitely gives it so the browser doesn't "guess" it (from font size, content or input content or whatever)
I also find the window a bit small (1st patch) but this is my personal preference.
